dynamixel_controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  leg_0_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - body_leg_0
      - leg_0_1_2
      - leg_0_2_3

  leg_1_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - body_leg_1
      - leg_1_1_2
      - leg_1_2_3

  leg_2_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - body_leg_2
      - leg_2_1_2
      - leg_2_2_3

  leg_3_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - body_leg_3
      - leg_3_1_2
      - leg_3_2_3

  leg_4_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - body_leg_4
      - leg_4_1_2
      - leg_4_2_3

  leg_5_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - body_leg_5
      - leg_5_1_2
      - leg_5_2_3

dynamixel_control_hw:
  loop_frequency: 50
  cycle_time_error_threshold: 0.1
  baudrate: 1000000 # in bauds
  dynamixel_timeout: 0.05 # in seconds
  # correspondance between hardware IDs of the actuators and their names in ROS
  hardware_mapping:
    body_leg_0: 1
    leg_0_1_2: 11
    leg_0_2_3: 21
    body_leg_1: 2
    leg_1_1_2: 12
    leg_1_2_3: 22
    body_leg_2: 3
    leg_2_1_2: 13
    leg_2_2_3: 23
    body_leg_3: 4
    leg_3_1_2: 14
    leg_3_2_3: 24
    body_leg_4: 5
    leg_4_1_2: 15
    leg_4_2_3: 25
    body_leg_5: 6
    leg_5_1_2: 16
    leg_5_2_3: 26
