<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
	<!-- XACRO MACRO FOR LEGS LINKS/JOINTS -->

    <xacro:macro name="leg" params="index xPos yPos sign">
        <joint name="body_leg_${index}" type="revolute">
            <parent link="base_link"/>
            <child link="leg_${index}_1"/>
            <limit effort="${joint_eff}" lower="${-joint_lim}" upper="${joint_lim}" velocity="${joint_vel}"/>
            <xacro:if value="${index == 5 or index == 2}">
                <origin rpy="0 0 -0.3" xyz="${xPos} ${yPos-sign*leg1_width} 0"/>
            </xacro:if>
            <xacro:if value="${index == 0 or index == 3}">
                <origin rpy="0 0 0.3" xyz="${xPos} ${yPos-sign*leg1_width} 0"/>
            </xacro:if>
            <xacro:if value="${index == 1 or index == 4}">
                <origin rpy="0 0 0" xyz="${xPos} ${yPos-sign*leg1_width} 0"/>
            </xacro:if>
            <!-- <xacro:if value="${index == 5 or index == 4 or index == 3}">
                <axis xyz="0 0 1"/>
            </xacro:if>
            <xacro:if value="${index == 2 or index == 1 or index == 0}"> -->
                <axis xyz="0 0 -1"/>
            <!-- </xacro:if> -->
            <dynamics damping="${joint_dmp}"/>
        </joint>
        <link name="leg_${index}_1">
            <xacro:visuals_collisions_leg_1 revert="${sign}"/>
            <inertial>
                <!-- CENTER OF MASS -->
                <origin rpy="${PI_2} 0 0" xyz="${leg1_width/2} ${sign*leg1_length/2} 0"/>
                <mass value="${leg1_mass}"/>
                <!-- Cylinder inertia: 1/12*m*(3*r^2+h^2), 1/12*m*(3*r^2+h^2), 1/12*m*r^2 -->
                <inertia ixx="${1/12*leg1_mass*(3*leg1_width*leg1_width+leg1_length*leg1_length)}" ixy="0" ixz="0" iyy="${1/12*leg1_mass*(3*leg1_width*leg1_width+leg1_length*leg1_length)}" iyz="0" izz="${1/12*leg1_mass*leg1_width*leg1_width}"/>
            </inertial>
        </link>
        <joint name="leg_${index}_1_2" type="revolute">
            <parent link="leg_${index}_1"/>
            <child link="leg_${index}_2"/>
            <limit effort="${joint_eff}" lower="${-joint_lim2}" upper="${joint_lim2}" velocity="${joint_vel}"/>
            <origin rpy="0 0 0" xyz="0 ${sign*leg1_length} 0"/>
            <xacro:if value="${index == 5 or index == 4 or index == 3}">
                <axis xyz="1 0 0"/>
            </xacro:if>
            <xacro:if value="${index == 2 or index == 1 or index == 0}">
                <axis xyz="-1 0 0"/>
            </xacro:if>
            <dynamics damping="${joint_dmp}"/>
        </joint>
        <link name="leg_${index}_2">
            <xacro:visuals_collisions_leg_2 revert="${sign}"/>
            <inertial>
                <!-- CENTER OF MASS -->
                <origin rpy="${PI_2} 0 0" xyz="${leg2_width/2} ${sign*leg2_length/2} 0"/>
                <mass value="${leg2_mass}"/>
                <!-- Cylinder inertia: 1/12*m*(3*r^2+h^2), 1/12*m*(3*r^2+h^2), 1/12*m*r^2 -->
                <inertia ixx="${1/12*leg2_mass*(3*leg2_width*leg2_width+leg2_length*leg2_length)}" ixy="0" ixz="0" iyy="${1/12*leg2_mass*(3*leg2_width*leg2_width+leg2_length*leg2_length)}" iyz="0" izz="${1/12*leg2_mass*leg2_width*leg2_width}"/>
            </inertial>
        </link>
        <joint name="leg_${index}_2_3" type="revolute">
            <parent link="leg_${index}_2"/>
            <child link="leg_${index}_3"/>
            <limit effort="${joint_eff}" lower="${-joint_lim2}" upper="${joint_lim2}" velocity="${joint_vel}"/>
            <origin rpy="${-sign*PI_2} 0 0" xyz="0 ${sign*leg2_length} 0"/>
            <xacro:if value="${index == 5 or index == 4 or index == 3}">
                <axis xyz="1 0 0"/>
            </xacro:if>
            <xacro:if value="${index == 2 or index == 1 or index == 0}">
                <axis xyz="-1 0 0"/>
            </xacro:if>
            <dynamics damping="${joint_dmp}"/>
        </joint>
        <link name="leg_${index}_3">
            <xacro:visuals_collisions_leg_3 revert="${sign}"/>
            <inertial>
                <!-- CENTER OF MASS -->
                <origin rpy="${PI_2} 0 0" xyz="${leg3_width/2} ${sign*leg3_length/2} 0"/>
                <mass value="${leg2_mass}"/>
                <!-- Cylinder inertia: 1/12*m*(3*r^2+h^2), 1/12*m*(3*r^2+h^2), 1/12*m*r^2 -->
                <inertia ixx="${1/12*leg2_mass*(3*leg2_width*leg2_width+leg2_length*leg2_length)}" ixy="0" ixz="0" iyy="${1/12*leg2_mass*(3*leg2_width*leg2_width+leg2_length*leg2_length)}" iyz="0" izz="${1/12*leg2_mass*leg2_width*leg2_width}"/>
            </inertial>
        </link>
    </xacro:macro>
    <!-- END OF LEG LINKS/JOINTS -->
</robot>
