<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- LEGS LINKS/JOINTS -->
    <xacro:leg index="2" xPos="${body_length/2}" yPos="${body_width/2}"/>
    <xacro:leg index="3" xPos="${body_length/2}" yPos="${-body_width/2}"/>


    <xacro:leg index="0" xPos="${-body_length/2}" yPos="${body_width/2}"/>
    <xacro:leg index="5" xPos="${-body_length/2}" yPos="${-body_width/2}"/>

    <xacro:leg index="1" xPos="0" yPos="${body_width_extra/2}"/>
    <xacro:leg index="4" xPos="0" yPos="${-body_width_extra/2}"/>
  <!-- END OF LEG LINKS/JOINTS -->
</robot>
